version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
